spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf
      ?useUnicode=true
      &createDatabaseIfNotExist=true
      &useJDBCCompliantTimezoneShift=true
      &useLegacyDatetimeCode=false
      &serverTimezone=UTC
    username: root
    password: 1234

server:
  port: 7070

